### PR TITLE
Added the command line option --nocolor

### PR DESCRIPTION
**Pull request by aashraybhandar1**
Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:

  - You made a small amount of changes (less than 100 lines, less than 10 files)
  - You made changes related to only one bug (create separate PRs for separate problems)
  - You are ready to defend your changes (there will be a code review)
  - You don't touch what you don't understand
  - You ran the build locally and it passed

This article will help you understand what we are looking for: http://www.yegor256.com/2015/02/09/serious-code-reviewer.html

Thank you for your contribution!

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#23](https://github.com/yegor256/xcop/issues/23) is now in scope, role is `REV`

**Comment by aashraybhandar1** [comment]
@yegor256  implemented the changes so ad to implement the `--nocolor` option

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by aashraybhandar1** [comment]
@yegor256 why is the merge failing?

**Comment by yegor256** [comment]
@rultor merge

**Comment by aashraybhandar1** [comment]
Thanks a lot @yegor256  😄 ... If I try to install via gem right now will these changes be included ?

**Comment by 0crat** [comment]
The job [#23](https://github.com/yegor256/xcop/issues/23) is now out of scope

**Comment by aashraybhandar1** [comment]
@yegor256  when will the new version be released for xcop ? Need it as a dependency for another project 😅

**Comment by yegor256** [comment]
@rultor release, tag is `0.6`

**Pull request merged**
